name: screen2green
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.5
  supabase_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/tempor-removebg-preview.png
    - assets/images/auth_plant.png
    - assets/images/dummy_plant.png
  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-VariableFont_wght.ttf